version: '1'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 11

  db:
    image: 'postgres:14'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11
      POSTGRES_DB: warehouse