spring:
  datasource:
    username: sa
    password: ${PWD}
    url: jdbc:h2:mem:warehouse;LOCK_TIMEOUT=60000
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml